site_name: Jacob GitLab Book
site_description: "Jacob's Gitlab Tutorial Book"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: "https://chao-xi.github.io/jxgitlabbook/"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'GitLab Fundamentals':
    - '4 Gitlab Issues and Timelines': 'chap0/4issues.md'
  - 'Gitlab 简介':
    - '1 Gitlab 基本介绍（CI/CD)' : 'chap1/1gitlab_cicd.md'
    - '2 Gitlab branch Strategy': 'chap1/2gitlab_branch_strategy.md'
    - '3 安装配置Gitlab': 'chap1/3gitlab_install_quick.md'
    - '4 在Kubernetes上安装Gitlab': 'chap1/4gitlab_install_k8s.md'
  - 'Gitlab Runner配置&安装':
    - '1 GitLab Runner 简介': 'chap2/1gitruner_intro.md'
    - '2 GitLab Runner安装注册配置管理': 'chap2/2gitrunner_install.md'
  - 'Pipeline 核心语法':
    - 'GitLabCI系列之流水线语法': 'chap3/1gitlab_pip1.md'
  - 'Gitlab工具链集成':
    - '1 模板库设计Maven+NPM': 'chap4/1git_template.md'
    - '2 Gitlab 工具链集成-代码质量平台集成': 'chap4/2git_sonar_pr.md'
    - '3 工具链集成-制品库集成': 'chap4/3gitlab_artifact_docker.md'
    - '4 Gitlab 自动化测试集成': 'chap4/4gitlab_jemeter.md'
  - 'Gitlab + Kubernetes集成':
    - '1 基于K8S安装部署Runner' : 'chap5/1gitlab-runner-install.md'
    - '2 Kubernetes 容器流水线': 'chap5/2gitlab_k8s.md'
    - '3 Kubernetes 流水线构建消息通知': 'chap5/3gitlab_notification.md'
    - '4 Gitlab + minio 配置使用分布式缓存': 'chap5/4gitlab_distri_storage.md'
  - 'Gitlab流水线最佳实践':
    - '1 流水线设计及提交': 'chap6/1pip_init.md'
    - '2 提交流水线设计': 'chap6/2pip_design.md'
    - '3 流水线运行': 'chap6/3pip_run.md'
  - '项目交付流水线':
    - '1 项目交付流水线优化后模板库配置': 'chap7/1deploy_pip.md'
    - '2 项目流水线(JAVA+NPM+安卓)': 'chap7/2deploy_projs.md'
  - 'gitlab Certified CICD':
    - 'GitLab Certified CI/CD Specialist Training': 'chap8/1cer_prep1.md'
    - 'Anatomy of a Pipeline': 'chap8/2pip_prep1.md'
    - 'Gitlab Pipeline 复习': 'chap8/3Gitlab_pip.md'


repo_url: https://github.com/Chao-Xi/jxgitlabbook.git
repo_name: "jxgitlabbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.jpeg'
  favicon: 'images/logo.jpeg'
  feature:
    tabs: false
  palette:
    primary: 'purple'
    accent: 'purple'
  i18n:
    prev: 'Previous'
    next: 'Next'