site_name: Jacob GitLab Book
site_description: "Jacob's Gitlab Tutorial Book"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: "https://chao-xi.github.io/jxgitlabbook/"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Gitlab 简介':
    - '1 Gitlab 基本介绍（CI/CD)' : 'chap1/1gitlab_cicd.md'
    - '2 Gitlab branch Strategy': 'chap1/2gitlab_branch_strategy.md'
    - '3 安装配置Gitlab': 'chap1/3gitlab_install_quick.md'
    - '4 在Kubernetes上安装Gitlab': 'chap1/4gitlab_install_k8s.md'

repo_url: https://github.com/Chao-Xi/jxgitlabbook.git
repo_name: "jxgitlabbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.jpeg'
  favicon: 'images/logo.jpeg'
  feature:
    tabs: false
  palette:
    primary: 'purple'
    accent: 'purple'
  i18n:
    prev: 'Previous'
    next: 'Next'