site_name: Jacob GitLab Book
site_description: "Jacob's Gitlab Tutorial Book"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: "https://chao-xi.github.io/jxgitlabbook/"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'GitLab Fundamentals':
    - 'Project and Repositoires': 'chap0/1proj.md'
    - 'Gitlab Issues and Timelines': 'chap0/4issues.md'
  - 'Gitlab 简介':
    - '1 Gitlab 基本介绍（CI/CD)' : 'chap1/1gitlab_cicd.md'
    - '2 Gitlab branch Strategy': 'chap1/2gitlab_branch_strategy.md'
    - '3 安装配置Gitlab': 'chap1/3gitlab_install_quick.md'
    - '4 在Kubernetes上安装Gitlab': 'chap1/4gitlab_install_k8s.md'
  - 'Gitlab Runner配置&安装':
    - '1 GitLab Runner 简介': 'chap2/1gitruner_intro.md'
    - '2 GitLab Runner安装注册配置管理': 'chap2/2gitrunner_install.md'
  - 'Pipeline 核心语法':
    - 'GitLabCI系列之流水线语法': 'chap3/1gitlab_pip1.md'
    - '2 Gitlab CI 流水线构建优化 + Runner构建优化（持久化）': 'chap3/2gitlab_summary.md'
  - 'Gitlab工具链集成':
    - '1 模板库设计Maven+NPM': 'chap4/1git_template.md'
    - '2 Gitlab 工具链集成-代码质量平台集成': 'chap4/2git_sonar_pr.md'
    - '3 工具链集成-制品库集成': 'chap4/3gitlab_artifact_docker.md'
    - '4 Gitlab 自动化测试集成': 'chap4/4gitlab_jemeter.md'
    - '5 GitLabCI/CD Prom构建数据采集与监控' : 'chap4/5gitlba_mon.md'
  - 'Gitlab + Kubernetes集成':
    - '1 基于K8S安装部署Runner' : 'chap5/1gitlab-runner-install.md'
    - '2 Kubernetes 容器流水线': 'chap5/2gitlab_k8s.md'
    - '3 Kubernetes 流水线构建消息通知': 'chap5/3gitlab_notification.md'
    - '4 Gitlab + minio 配置使用分布式缓存': 'chap5/4gitlab_distri_storage.md'
  - 'Gitlab流水线最佳实践':
    - '1 流水线设计及提交': 'chap6/1pip_init.md'
    - '2 提交流水线设计': 'chap6/2pip_design.md'
    - '3 流水线运行': 'chap6/3pip_run.md'
    - '4 如何将Secrets扫描加入到GitLab Pipeline': 'chap6/4pip_secret.md'
  - '项目交付流水线':
    - '1 项目交付流水线优化后模板库配置': 'chap7/1deploy_pip.md'
    - '2 项目流水线(JAVA+NPM+安卓)': 'chap7/2deploy_projs.md'
  - 'gitlab Certified CICD':
    - 'GitLab Certified CI/CD Specialist Training': 'chap8/1cer_prep1.md'
    - 'Anatomy of a Pipeline': 'chap8/2pip_prep1.md'
    - 'Gitlab Pipeline 复习': 'chap8/3Gitlab_pip.md'
    - 'Gitlab 认证考题': 'chap8/4Final_test.md'
  - 'gitlab Project Management':
    - 'L1 Gitlab branch Strategy': 'chap9/1Gitlab_branch.md'
    - 'L2 Gitflow Workflow': 'chap9/2gitlab_workflow.md'
    - 'L3 Gitlab branch Settup Action': 'chap9/3Gitlab_branch_action.md'
    - 'L4 Agile Planning with GitLab': 'chap9/4gitlab_project.md'
    - 'L5 Using Git Commit Message Templates': 'chap9/4gitlab_project.md'
  - 'ArgoCD Project':
    - '0 GitOps 常用工具盘点': 'argo1/0gitops.md'
    - '1 使用 Argo CD 进行 GitOps 流水线改造- 2024': 'argo1/1argo2023_gitops.md'
    - '2 使用 Argo Rollouts 实现应用渐进式发布': 'argo1/2Argo_Rollouts.md'
    - '3 DevOps中的Argo CD — 灾难恢复': 'argo1/3argo_dr.md'
    - '4 A/B测试: 如何使用Argo Rollouts 进行渐进式交付': 'argo1/4argo_rollouts_ab.md'
    - '5 GitOps 简介': 'argo1/6gitops.md'
    - '6 K8S YAML 资源清单管理方案': 'argo1/7k8s_yaml_cicd.md'
    - '7 ArgoCD Image Updater': 'argo1/8cd_image_updater.md'
    
  - 'Github Action':
    - '基于GitHubActions同步Docker镜像实践': 'chap10/1action_docker.md'
    - 'GitHub Action - CI/CD Pipeline with Docker': 'chap10/2action_workflow.md'
    - 'GitHub Actions basic learning': 'chap10/3action_events.md'

repo_url: https://github.com/Chao-Xi/jxgitlabbook.git
repo_name: "jxgitlabbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.jpeg'
  favicon: 'images/logo.jpeg'
  feature:
    tabs: false
  palette:
    primary: 'purple'
    accent: 'purple'
  i18n:
    prev: 'Previous'
    next: 'Next'